name: Client Build

on:
  push:
    branches: [dev]
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Build # 의존 파일 설치
        run: |
          cd client
          yarn
          yarn build
          mv build ../build
          cd ..
          tar -cvzf build.tgz appspec.yml build
        env:
          CI: false

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            build.tgz s3://bmart-8/client_build/build.tgz

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: '-rltgoDzvO'
          SOURCE: 'client/build/'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TARGET: './bmart/client/build/'
